name: build

on:
  pull_request:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: acorn-io/actions-setup@v2
        with:
          acorn-version: main
      - name: Build
        run: |
          acorn build -t ghcr.io/${{ github.repository_owner }}/website:latest .
