name: build

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: acorn-io/actions-setup@v2
        with:
          acorn-version: main
      - uses: acorn-io/actions-login@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          acorn build --push -t ghcr.io/${{ github.repository_owner }}/website:latest .
